# Generated by Django 5.2.6 on 2025-11-15 14:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soilcore', '0001_initial'),
        ('soildata', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CropHealthPrediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ph', models.FloatField()),
                ('temperature', models.FloatField()),
                ('moisture', models.FloatField()),
                ('salinity', models.FloatField()),
                ('risk_level', models.CharField(max_length=20)),
                ('predicted_at', models.DateTimeField(auto_now_add=True)),
                ('soil_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='soilcore.soiltype')),
            ],
        ),
    ]
