# Generated by Django 4.2 on 2025-11-18 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('soildata', '0003_communitypost'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='devicereading',
            name='device',
        ),
        migrations.DeleteModel(
            name='Device',
        ),
        migrations.DeleteModel(
            name='DeviceReading',
        ),
    ]
